# Generated by Django 2.2 on 2021-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
