# Generated by Django 2.2 on 2021-07-02 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210629_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 2, 8, 50, 876100, tzinfo=utc)),
        ),
    ]
